# @generated
# @autocargo from //hphp/hack/src/hhbc:runtime
# Signature<<6f9af1e56c1d5d79dd5a3a8a6ad201231626d770>>
[package]
name = "runtime"
edition = "2018"
version = "0.0.0"
include = ["../../typed_value.rs"]

[lib]
path = "../../typed_value.rs"

[dependencies]
hhbc_string_utils_rust = { path = "../string_utils" }
oxidized = { path = "../../../oxidized" }
lazy_static = "*"
# @end of Signature<<6f9af1e56c1d5d79dd5a3a8a6ad201231626d770>>
