# @generated
# @autocargo from //hphp/hack/src/parser:decl_mode_smart_constructors
# Signature<<eef5f69c06047f3b1de45c7806498d7e13ff8ea1>>
[package]
name = "decl_mode_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../decl_mode_smart_constructors.rs", "../../decl_mode_smart_constructors_generated.rs"]

[lib]
path = "../../decl_mode_smart_constructors.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
smart_constructors = { path = "../smart_constructors" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<eef5f69c06047f3b1de45c7806498d7e13ff8ea1>>
