# @generated
# @autocargo from //hphp/hack/src/parser:decl_mode_parser
# Signature<<064d9b5e7133feb01d1cdda1ab09b90ce14f709c>>
[package]
name = "decl_mode_parser"
edition = "2018"
version = "0.0.0"
include = ["../../decl_mode_parser.rs", "../../decl_mode_smart_constructors.rs", "../../decl_mode_smart_constructors_generated.rs"]

[lib]
path = "../../decl_mode_parser.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<064d9b5e7133feb01d1cdda1ab09b90ce14f709c>>
