# @generated
# @autocargo from //hphp/hack/src/name_index/sqlite:names
# Signature
[package]
name = "names"
edition = "2018"
version = "0.0.0"
include = ["consts.rs", "datatypes.rs", "file_infos.rs", "funs.rs", "lib.rs", "names.rs"]

[lib]
path = "lib.rs"

[dependencies]
ocamlrep = { path = "../../ocamlrep" }
oxidized = { path = "../../oxidized" }
rusqlite = "0.21"
rust-crypto = "0.2"
# @end of Signature
