# @generated
# @autocargo from //hphp/hack/src/hhbc:ast_class_expr_rust
# Signature<<6791bb52c255ba716a97167882035ae4bedec7d3>>
[package]
name = "ast_class_expr_rust"
edition = "2018"
version = "0.0.0"
include = ["../../ast_class_expr.rs"]

[lib]
path = "../../ast_class_expr.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
env = { path = "../env" }
hhbc_ast_rust = { path = "../hhbc_ast" }
hhbc_string_utils_rust = { path = "../string_utils" }
instruction_sequence_rust = { path = "../instruction_sequence" }
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<6791bb52c255ba716a97167882035ae4bedec7d3>>
