# @generated
# @autocargo from //hphp/hack/src/parser:minimal_parser_ffi
# Signature<<f91c423fa66e23617027c42b3669b0808d4f9956>>
[package]
name = "minimal_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../minimal_parser_ffi.rs"]

[lib]
path = "../../minimal_parser_ffi.rs"

[dependencies]
minimal_parser = { path = "../../api/cargo/minimal_parser" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<f91c423fa66e23617027c42b3669b0808d4f9956>>
