# @generated
# @autocargo from //hphp/hack/src/parser:operator
# Signature<<fd35cda78b6f2371fa76d9dd18ffd730646d7358>>
[package]
name = "operator"
edition = "2018"
version = "0.0.0"
include = ["../../operator.rs", "../../operator_generated.rs"]

[lib]
path = "../../operator.rs"

[dependencies]
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_derive = { path = "../../../ocamlrep_derive" }
parser_core_types = { path = "../core_types" }
# @end of Signature<<fd35cda78b6f2371fa76d9dd18ffd730646d7358>>
