# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_type_constant_rust
# Signature<<84fd07dfeb42e8ead10f0b2fdd4577ed2c0a1f95>>
[package]
name = "emit_type_constant_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_type_constant.rs"]

[lib]
path = "../../emit_type_constant.rs"

[dependencies]
hhbc_id_rust = { path = "../hhbc_id" }
hhbc_string_utils_rust = { path = "../string_utils" }
naming_special_names_rust = { path = "../../../naming" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
# @end of Signature<<84fd07dfeb42e8ead10f0b2fdd4577ed2c0a1f95>>
