# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_type_constant_rust
# Signature<<b0e93af98d601af7a070875f963db36519502239>>
[package]
name = "emit_type_constant_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_type_constant.rs"]

[lib]
path = "../../emit_type_constant.rs"

[dependencies]
hhbc_id_rust = { path = "../hhbc_id" }
hhbc_string_utils_rust = { path = "../string_utils" }
naming_special_names_rust = { path = "../../../naming" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
# @end of Signature<<b0e93af98d601af7a070875f963db36519502239>>
