# @generated
# @autocargo from //hphp/hack/src/parser/api:positioned_parser
# Signature<<98d2ea54ab34815c43e186643a134330957c7830>>
[package]
name = "positioned_parser"
edition = "2018"
version = "0.0.0"
include = ["../../positioned_parser.rs"]

[lib]
path = "../../positioned_parser.rs"

[dependencies]
parser = { path = "../../../core" }
positioned_smart_constructors = { path = "../../../cargo/positioned_smart_constructors" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<98d2ea54ab34815c43e186643a134330957c7830>>
