# @autocargo from //hphp/hack/src/decl:decl_rust_ffi
# Signature<<f6c46f0f9ef7971792838a604a142967d4a712cc>>
[package]
name = "decl_rust_ffi"
edition = "2018"
version = "0.0.0"
include = ["../rust_decl_ffi.rs"]

[lib]
path = "../rust_decl_ffi.rs"

[dependencies]
decl_rust = { path = ".." }
ocamlrep_ocamlpool = { path = "../../ocamlrep_ocamlpool" }
oxidized = { path = "../../oxidized" }
# @end of Signature<<f6c46f0f9ef7971792838a604a142967d4a712cc>>
