# @generated
# @autocargo from //hphp/hack/src/hhbc:options_serde
# Signature<<317aa9455700dc5c8fdd6884f83a238717b2af97>>
[package]
name = "options_serde"
edition = "2018"
version = "0.0.0"
include = ["../../options_serde.rs"]

[lib]
path = "../../options_serde.rs"
proc-macro = true
test = false
doctest = false

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = { version = "1.0", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
# @end of Signature<<317aa9455700dc5c8fdd6884f83a238717b2af97>>
