# @autocargo from //hphp/hack/src/hhbc:options_serde
# Signature<<ebc8092a3afd54d1593cd411fbfccb4e28fc89db>>
[package]
name = "options_serde"
edition = "2018"
version = "0.0.0"
include = ["../../options_serde.rs"]

[lib]
path = "../../options_serde.rs"
proc-macro = true
test = false
doctest = false

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
# @end of Signature<<ebc8092a3afd54d1593cd411fbfccb4e28fc89db>>
