# @generated
# @autocargo from //hphp/hack/src/parser:rust_editable_positioned_syntax
# Signature<<feb9e68c68ef63c726ba58e424c2550548c07273>>
[package]
name = "rust_editable_positioned_syntax"
edition = "2018"
version = "0.0.0"
include = ["../../editable_positioned_original_source_data.rs", "../../editable_positioned_syntax.rs", "../../editable_positioned_syntax_to_ocaml.rs", "../../editable_positioned_token.rs"]

[lib]
path = "../../editable_positioned_syntax.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
ocaml = "0.8"
# @end of Signature<<feb9e68c68ef63c726ba58e424c2550548c07273>>
