# @generated
# @autocargo from //hphp/hack/src/parser:coroutine_smart_constructors
# Signature<<2c442d79c7b2bdafff653d839a47df18a2e20a56>>
[package]
name = "coroutine_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_smart_constructors.rs", "../../coroutine_smart_constructors_generated.rs"]

[lib]
path = "../../coroutine_smart_constructors.rs"

[dependencies]
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<2c442d79c7b2bdafff653d839a47df18a2e20a56>>
