# @generated
# @autocargo from //hphp/hack/src/parser:coroutine_smart_constructors
# Signature<<52bebac8e864ec6ca0c8c0eef5183d7c0b2a634b>>
[package]
name = "coroutine_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_smart_constructors.rs", "../../coroutine_smart_constructors_generated.rs"]

[lib]
path = "../../coroutine_smart_constructors.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<52bebac8e864ec6ca0c8c0eef5183d7c0b2a634b>>
