# @generated
# @autocargo from //hphp/hack/src/parser:coroutine_smart_constructors
# Signature<<52ebd0afef4b2509c4e55c3755d6865b29dae2d9>>
[package]
name = "coroutine_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_smart_constructors.rs", "../../coroutine_smart_constructors_generated.rs"]

[lib]
path = "../../coroutine_smart_constructors.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
smart_constructors = { path = "../smart_constructors" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<52ebd0afef4b2509c4e55c3755d6865b29dae2d9>>
