# @generated
# @autocargo from //hphp/hack/src/parser:ocaml_syntax
# Signature<<14e205cd77e4c2e2b5b30e814bdef0e9f6f2f437>>
[package]
name = "ocaml_syntax"
edition = "2018"
version = "0.0.0"
include = ["../../ocaml_coroutine_state.rs", "../../ocaml_syntax.rs", "../../ocaml_syntax_generated.rs"]

[lib]
path = "../../ocaml_syntax.rs"

[dependencies]
coroutine_smart_constructors = { path = "../coroutine_smart_constructors" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<14e205cd77e4c2e2b5b30e814bdef0e9f6f2f437>>
