# @autocargo from //hphp/hack/src/parser:rust_parser_errors
# Signature<<bef68e8440e47b3bc4a5e29b29acefdc24b7def6>>
[package]
name = "rust_parser_errors"
edition = "2018"
version = "0.0.0"
include = ["../../rust_parser_errors.rs"]

[lib]
path = "../../rust_parser_errors.rs"

[dependencies]
hh_autoimport_rust = { path = "../hh_autoimport" }
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
syntax_tree = { path = "../syntax_tree" }
itertools = "*"
lazy_static = "*"
regex = "*"
# @end of Signature<<bef68e8440e47b3bc4a5e29b29acefdc24b7def6>>
