# @generated
# @autocargo from //hphp/hack/src/parser:rust_parser_errors
# Signature<<27ce31459c2f32911c57f874bb262e161c87d778>>
[package]
name = "rust_parser_errors"
edition = "2018"
version = "0.0.0"
include = ["../../rust_parser_errors.rs"]

[lib]
path = "../../rust_parser_errors.rs"

[dependencies]
hh_autoimport_rust = { path = "../hh_autoimport" }
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
syntax_tree = { path = "../syntax_tree" }
itertools = "0.8"
lazy_static = "1.4"
regex = "1.3"
# @end of Signature<<27ce31459c2f32911c57f874bb262e161c87d778>>
