[package]
name = "hack_parser_ffi"
version = "3.49.0"
edition = "2021"

[dependencies]
verify_parser_ffi = { path = "../cargo/verify_parser_ffi", package = "verify_parser_ffi" }
aast_parser_ffi = { path = "../cargo/aast_parser_ffi", package = "aast_parser_ffi" }
positioned_by_ref_parser_ffi = { path = "../cargo/positioned_by_ref_parser_ffi", package = "positioned_by_ref_parser_ffi" }

[lib]
name = "rust_parser_ffi"
path = "lib.rs"
crate-type = ["lib", "staticlib"]
