# @generated
# @autocargo from //hphp/hack/src/hhbc:local_rust
# Signature
[package]
name = "local_rust"
edition = "2018"
version = "0.0.0"
include = ["../../local.rs"]

[lib]
path = "../../local.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
lazy_static = "1.0"
# @end of Signature
