# @generated
# @autocargo from //hphp/hack/src/hhbc:local_rust
# Signature<<2b71dff221b5e7e7e96e92261253b34193d18c12>>
[package]
name = "local_rust"
edition = "2018"
version = "0.0.0"
include = ["../../local.rs"]

[lib]
path = "../../local.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
lazy_static = "*"
# @end of Signature<<2b71dff221b5e7e7e96e92261253b34193d18c12>>
