# @autocargo from //hphp/hack/src/hhbc:unique_list_rust
# Signature<<4107484c5ce821fa0db23cf7caf023585bb7ae14>>
[package]
name = "unique_list_rust"
edition = "2018"
version = "0.0.0"
include = ["../../unique_list.rs"]

[lib]
path = "../../unique_list.rs"

[dependencies]
indexmap = "*"
# @end of Signature<<4107484c5ce821fa0db23cf7caf023585bb7ae14>>
