# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_property_rust
# Signature<<0fe7e41d082c3225345fbeceba137985cbbbe883>>
[package]
name = "hhas_property_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_property.rs"]

[lib]
path = "../../hhas_property.rs"

[dependencies]
env = { path = "../env" }
hhas_attribute_rust = { path = "../hhas_attribute" }
hhas_type = { path = "../hhas_type" }
hhbc_id_rust = { path = "../hhbc_id" }
instruction_sequence_rust = { path = "../instruction_sequence" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
bitflags = "*"
# @end of Signature<<0fe7e41d082c3225345fbeceba137985cbbbe883>>
