# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_attribute_rust
# Signature<<465de627565d1579d46b5e160e74b6a90b7499dd>>
[package]
name = "emit_attribute_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_attribute.rs"]

[lib]
path = "../../emit_attribute.rs"

[dependencies]
ast_constant_folder_rust = { path = "../ast_constant_folder" }
emit_expression_rust = { path = "../.." }
emit_fatal_rust = { path = "../emit_fatal" }
env = { path = "../env" }
escaper = { path = "../../../utils/escaper" }
hhas_attribute_rust = { path = "../hhas_attribute" }
hhbc_id_rust = { path = "../hhbc_id" }
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
itertools = "0.8"
# @end of Signature<<465de627565d1579d46b5e160e74b6a90b7499dd>>
