# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_ast_rust
# Signature<<13c0dd5d8ad973952fbc8bb7dca931614952396f>>
[package]
name = "hhbc_ast_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhbc_ast.rs"]

[lib]
path = "../../hhbc_ast.rs"

[dependencies]
env = { path = "../env" }
hhbc_id_rust = { path = "../hhbc_id" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
runtime = { path = "../runtime" }
bitflags = "*"
# @end of Signature<<13c0dd5d8ad973952fbc8bb7dca931614952396f>>
