# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_ast_rust
# Signature<<3b820592d9f665d90f24cdff7d09a39199878693>>
[package]
name = "hhbc_ast_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhbc_ast.rs"]

[lib]
path = "../../hhbc_ast.rs"

[dependencies]
env = { path = "../env" }
hhbc_id_rust = { path = "../hhbc_id" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
runtime = { path = "../runtime" }
bitflags = "1.2"
# @end of Signature<<3b820592d9f665d90f24cdff7d09a39199878693>>
