# @generated
# @autocargo from //hphp/hack/src/hhbc:label_rust
# Signature<<db4f202ec14d6ca658ec3586821027b0288594be>>
[package]
name = "label_rust"
edition = "2018"
version = "0.0.0"
include = ["../../label.rs"]

[lib]
path = "../../label.rs"
# @end of Signature<<db4f202ec14d6ca658ec3586821027b0288594be>>
