# @generated
# @autocargo from //hphp/hack/src/hhbc:ast_scope_rust
# Signature<<888f851ab4b53a0a59bb30839711e7f999a93503>>
[package]
name = "ast_scope_rust"
edition = "2018"
version = "0.0.0"
include = ["../../ast_scope.rs"]

[lib]
path = "../../ast_scope.rs"

[dependencies]
oxidized = { path = "../../../oxidized" }
rx_rust = { path = "../rx" }
# @end of Signature<<888f851ab4b53a0a59bb30839711e7f999a93503>>
