# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_symbol_refs_rust
# Signature<<9e38ee3942262a4a2b5a3e552c6516bb1bf6dc4a>>
[package]
name = "hhas_symbol_refs_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_symbol_refs.rs"]

[lib]
path = "../../hhas_symbol_refs.rs"
# @end of Signature<<9e38ee3942262a4a2b5a3e552c6516bb1bf6dc4a>>
