# @generated
# @autocargo from //hphp/hack/src/parser:parser_rust
# Signature<<ae7bc41318fc630de8699c1560f8664785f24796>>
[package]
name = "parser_rust"
edition = "2018"
version = "0.0.0"
include = ["declaration_parser.rs", "expression_parser.rs", "lexer.rs", "lib.rs", "operator.rs", "operator_generated.rs", "parser.rs", "parser_trait.rs", "rewriter.rs", "smart_constructors.rs", "smart_constructors_generated.rs", "smart_constructors_macros.rs", "smart_constructors_wrappers.rs", "statement_parser.rs", "type_parser.rs"]

[lib]
path = "lib.rs"

[dependencies]
hh_autoimport_rust = { path = "cargo/hh_autoimport" }
ocamlrep = { path = "../ocamlrep" }
ocamlrep_derive = { path = "../ocamlrep_derive" }
oxidized = { path = "../oxidized" }
parser_core_types = { path = "cargo/core_types" }
stack_limit = { path = "../utils/stack_limit" }
lazy_static = "1.4"
ocaml = "0.8"
# @end of Signature<<ae7bc41318fc630de8699c1560f8664785f24796>>
