[package]
name = "hack_parser"
version = "3.49.0"
edition = "2018"

[lib]
name = "parser_rust"
path = "lib.rs"

[dependencies]
lazy_static = "^1.3.0"
parser_core_types = { path = "cargo/core_types", package = "hack_parser_core_types" }
oxidized = { path = "../oxidized", package = "hack_oxidized" }
ocamlrep = { path = "../ocamlrep", package = "hack_ocamlrep" }
ocamlrep_derive = { path = "../ocamlrep_derive", package = "hack_ocamlrep_derive" }
stack_limit = { path = "../utils/stack_limit", package = "hack_stack_limit" }
