[package]
name = "hack_parser"
version = "3.49.0"
edition = "2018"

[lib]
name = "parser_rust"
path = "lib.rs"

[dependencies]
deps_rust = { path = "../deps", package = "hack_deps" }
ocaml = "^0.7"
lazy_static = "^1.3.0"
