[package]
name = "decl_mode_parser_ffi"
version = "3.49.0"
edition = "2018"

[lib]
name = "decl_mode_parser_ffi"
path = "../../decl_mode_parser_ffi.rs"

[dependencies]
positioned_parser = { path = "../positioned_parser", package = "positioned_parser" }
parser_rust = { path = "../..", package = "parser_rust" }
syntax_tree = { path = "../syntax_tree", package = "syntax_tree" }
libc = "^0.2.60"
decl_mode_parser = { path = "../decl_mode_parser", package = "decl_mode_parser" }
parser_core_types = { path = "../core_types", package = "parser_core_types" }
rust_parser_ffi = { path = "../rust_parser_ffi", package = "rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml", package = "rust_to_ocaml" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust", package = "ocamlpool_rust" }
ocaml = "^0.7"
ocamlrep = { path = "../../../ocamlrep", package = "ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool", package = "ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized", package = "oxidized" }
