# @generated
# @autocargo from //hphp/hack/src/parser:decl_mode_parser_ffi
# Signature<<08b4a4eabe9235a3351b051bc12f89666585b3b6>>
[package]
name = "decl_mode_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../decl_mode_parser_ffi.rs"]

[lib]
path = "../../decl_mode_parser_ffi.rs"

[dependencies]
decl_mode_parser = { path = "../decl_mode_parser" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<08b4a4eabe9235a3351b051bc12f89666585b3b6>>
