[package]
name = "serde_bser"
version = "0.3.1"
authors = ["Rain <rain1@fb.com>", "Wez Furlong"]
edition = "2021"
description = "Implements the Watchman BSER encoding for serde. https://facebook.github.io/watchman/docs/bser.html"
documentation = "https://docs.rs/serde_bser"
repository = "https://github.com/facebook/watchman/"
license = "MIT"

[dependencies]
anyhow = "1.0"
byteorder = "1.3"
bytes = { version = "1.0", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_bytes = "0.11"
thiserror = "1.0"

[dev-dependencies]
maplit = "1.0"

[features]
debug_bytes = []
default = []
