# @generated
# @autocargo from //hphp/hack/src/parser:syntax_tree
# Signature<<68eb2cc07e8c10d72fe813f7e8addf2530c28c8c>>
[package]
name = "syntax_tree"
edition = "2018"
version = "0.0.0"
include = ["../../mode_parser.rs", "../../syntax_tree.rs"]

[lib]
path = "../../syntax_tree.rs"

[dependencies]
minimal_parser = { path = "../minimal_parser" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
stack_limit = { path = "../../../utils/stack_limit" }
# @end of Signature<<68eb2cc07e8c10d72fe813f7e8addf2530c28c8c>>
