# @autocargo from //hphp/hack/src/parser:syntax_tree
# Signature<<b18dea9f9af83c76e2f47d2b38ca600bd3467027>>
[package]
name = "syntax_tree"
edition = "2018"
version = "0.0.0"
include = ["../../mode_parser.rs", "../../syntax_tree.rs"]

[lib]
path = "../../syntax_tree.rs"

[dependencies]
minimal_parser = { path = "../minimal_parser" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
stack_limit = { path = "../../../utils/stack_limit" }
# @end of Signature<<b18dea9f9af83c76e2f47d2b38ca600bd3467027>>
