# @autocargo from //hphp/hack/src/hhbc:hhas_type
# Signature<<3dfa77bc8db2e19db8807166427705b80ddde8ed>>
[package]
name = "hhas_type"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_type.rs"]

[lib]
path = "../../hhas_type.rs"

[dependencies]
emit_fatal_rust = { path = "../emit_fatal" }
bitflags = "*"
# @end of Signature<<3dfa77bc8db2e19db8807166427705b80ddde8ed>>
