# @generated
# @autocargo from //hphp/hack/src/utils:ocaml_helper
# Signature<<a4c84038d93bdd376dd7112f80bfb392621b1fa9>>
[package]
name = "ocaml_helper"
edition = "2018"
version = "0.0.0"
include = ["../ocaml_helper.rs"]

[lib]
path = "../ocaml_helper.rs"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<a4c84038d93bdd376dd7112f80bfb392621b1fa9>>
