# @generated
# @autocargo from //hphp/hack/src/parser:positioned_parser
# Signature<<c968153b8b57dc4f9750ab2bf851c08d890df185>>
[package]
name = "positioned_parser"
edition = "2018"
version = "0.0.0"
include = ["../../positioned_parser.rs", "../../positioned_smart_constructors.rs"]

[lib]
path = "../../positioned_parser.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
# @end of Signature<<c968153b8b57dc4f9750ab2bf851c08d890df185>>
