# @generated
# @autocargo from //hphp/hack/src/parser:verify_parser_ffi
# Signature<<160b6a22e8627c37fd93941c9a4978b7816c58f7>>
[package]
name = "verify_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../verify_parser_ffi.rs"]

[lib]
path = "../../verify_parser_ffi.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
verify_parser = { path = "../verify_parser" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<160b6a22e8627c37fd93941c9a4978b7816c58f7>>
