# @autocargo from //hphp/hack/src/hhbc:scope_rust
# Signature<<c33442b731f4b587b188874b3d17fc38a21597d3>>
[package]
name = "scope_rust"
edition = "2018"
version = "0.0.0"
include = ["../../scope.rs"]

[lib]
path = "../../scope.rs"

[dependencies]
env = { path = "../env" }
instruction_sequence_rust = { path = "../instruction_sequence" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
# @end of Signature<<c33442b731f4b587b188874b3d17fc38a21597d3>>
