# @generated
# @autocargo from //hphp/hack/src/parser/api:facts_parser
# Signature<<0f211955c5c524799246369e68467ae661dffa9a>>
[package]
name = "facts_parser"
edition = "2018"
version = "0.0.0"
include = ["../../facts_parser.rs"]

[lib]
path = "../../facts_parser.rs"

[dependencies]
facts_smart_constructors = { path = "../../../../facts/cargo/facts_smart_constructors" }
parser = { path = "../../../core" }
parser_core_types = { path = "../../../cargo/core_types" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<0f211955c5c524799246369e68467ae661dffa9a>>
