# @generated
# @autocargo from //hphp/hack/src/parser/api:minimal_parser
# Signature<<acaa982562d99bb430dd0d3e0e35a2c49f8f2a8e>>
[package]
name = "minimal_parser"
edition = "2018"
version = "0.0.0"
include = ["../../minimal_parser.rs"]

[lib]
path = "../../minimal_parser.rs"

[dependencies]
minimal_smart_constructors = { path = "../../../cargo/minimal_parser" }
parser = { path = "../../../core" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<acaa982562d99bb430dd0d3e0e35a2c49f8f2a8e>>
