# @generated
# @autocargo from //hphp/hack/src/parser/api:direct_decl_parser
# Signature<<3eade6f280f190bff29a2757c15d4c8f35afb540>>
[package]
name = "direct_decl_parser"
edition = "2018"
version = "0.0.0"
include = ["../../direct_decl_parser.rs"]

[lib]
path = "../../direct_decl_parser.rs"

[dependencies]
direct_decl_smart_constructors = { path = "../../../../decl/direct_decl_smart_constructors" }
parser = { path = "../../../core" }
parser_core_types = { path = "../../../cargo/core_types" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<3eade6f280f190bff29a2757c15d4c8f35afb540>>
