# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_type_hint_rust
# Signature<<37a2a15ea9a871d25917c9c62ec8ed699516764c>>
[package]
name = "emit_type_hint_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_type_hint.rs"]

[lib]
path = "../../emit_type_hint.rs"

[dependencies]
emit_fatal_rust = { path = "../emit_fatal" }
hhas_type = { path = "../hhas_type" }
hhbc_id_rust = { path = "../hhbc_id" }
hhbc_string_utils_rust = { path = "../string_utils" }
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<37a2a15ea9a871d25917c9c62ec8ed699516764c>>
