# @generated
# @autocargo from //hphp/hack/src/parser:verify_parser
# Signature<<65fced711482a0663485c38ceb9b15783b4a1194>>
[package]
name = "verify_parser"
edition = "2018"
version = "0.0.0"
include = ["../../verify_parser.rs", "../../verify_smart_constructors.rs", "../../verify_smart_constructors_generated.rs"]

[lib]
path = "../../verify_parser.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "*"
# @end of Signature<<65fced711482a0663485c38ceb9b15783b4a1194>>
