# @generated
# @autocargo from //hphp/hack/src/parser:verify_parser
# Signature<<d5de30d70007c955c29436552ec2063dc7b73362>>
[package]
name = "verify_parser"
edition = "2018"
version = "0.0.0"
include = ["../../verify_parser.rs", "../../verify_smart_constructors.rs", "../../verify_smart_constructors_generated.rs"]

[lib]
path = "../../verify_parser.rs"

[dependencies]
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<d5de30d70007c955c29436552ec2063dc7b73362>>
