# @generated
# @autocargo from //hphp/hack/src/decl:decl_rust
# Signature<<b3082c108460f7634f41638a5f89c838a06bb0f9>>
[package]
name = "decl_rust"
edition = "2018"
version = "0.0.0"
include = ["direct_decl_parser.rs", "direct_decl_smart_constructors.rs", "direct_decl_smart_constructors_generated.rs", "lib.rs"]

[lib]
path = "lib.rs"

[dependencies]
flatten_smart_constructors = { path = "../parser/cargo/flatten_smart_constructors" }
hh_autoimport_rust = { path = "../parser/cargo/hh_autoimport" }
hhbc_string_utils_rust = { path = "../hhbc/cargo/string_utils" }
naming_special_names_rust = { path = "../naming" }
ocamlrep = { path = "../ocamlrep" }
oxidized = { path = "../oxidized" }
parser_rust = { path = "../parser" }
syntax_tree = { path = "../parser/cargo/syntax_tree" }
rust-crypto = "*"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<b3082c108460f7634f41638a5f89c838a06bb0f9>>
