# @generated
# @autocargo from //hphp/hack/src/facts:facts_rust
# Signature<<262496c4465b19ecf266c2a934e1cb106879bbc8>>
[package]
name = "facts_rust"
edition = "2018"
version = "0.0.0"
include = ["facts.rs", "facts_parser.rs", "facts_smart_constructors.rs", "facts_smart_constructors_generated.rs", "lib.rs"]

[lib]
path = "lib.rs"

[dependencies]
escaper = { path = "../utils/escaper" }
flatten_smart_constructors = { path = "../parser/cargo/flatten_smart_constructors" }
hhbc_string_utils_rust = { path = "../hhbc/cargo/string_utils" }
ocamlrep = { path = "../ocamlrep" }
oxidized = { path = "../oxidized" }
parser_rust = { path = "../parser" }
syntax_tree = { path = "../parser/cargo/syntax_tree" }
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<262496c4465b19ecf266c2a934e1cb106879bbc8>>
