# @generated
# @autocargo from //hphp/hack/src/facts:facts_rust
# Signature<<9c4309ddc3c6c3ee11705359c38dd7ab960f6f5b>>
[package]
name = "facts_rust"
edition = "2018"
version = "0.0.0"
include = ["facts.rs", "facts_parser.rs", "facts_smart_constructors.rs", "facts_smart_constructors_generated.rs", "lib.rs"]

[lib]
path = "lib.rs"

[dependencies]
escaper = { path = "../utils/escaper" }
flatten_smart_constructors = { path = "../parser/cargo/flatten_smart_constructors" }
hhbc_string_utils_rust = { path = "../hhbc/cargo/string_utils" }
ocamlrep = { path = "../ocamlrep" }
oxidized = { path = "../oxidized" }
parser_rust = { path = "../parser" }
syntax_tree = { path = "../parser/cargo/syntax_tree" }
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<9c4309ddc3c6c3ee11705359c38dd7ab960f6f5b>>
