[package]
name = "hack_facts"
version = "3.49.0"
edition = "2018"

[lib]
name = "facts_rust"
path = "lib.rs"

[dependencies]
parser_rust = { path = "../parser", package = "hack_parser" }
flatten_smart_constructors = { path = "../parser/cargo/flatten_smart_constructors", package = "flatten_smart_constructors" }
syntax_tree = { path = "../parser/cargo/syntax_tree", package = "syntax_tree" }
rust-crypto = "^0.2"
serde = "^1.0.98"
serde_derive = "^1.0.98"
serde_json = "^1.0.40"
hhbc_string_utils_rust = { path = "../hhbc/cargo/string_utils", package = "hack_hhbc_string_utils" }
ocamlrep = {path = "../ocamlrep", package = "hack_ocamlrep" }
oxidized = {path = "../oxidized", package = "hack_oxidized" }
escaper = {path = "../utils/escaper", package = "hack_escaper"}

[dev-dependencies]
pretty_assertions = "^0.6.1"
