# @generated
# @autocargo from //hphp/hack/src/parser/bench:bench
# Signature<<7ceb084244748a256f28be1d047aa133e18a6a74>>
[package]
name = "bench"
edition = "2018"
version = "0.0.0"
include = ["../../bench/bench.rs"]

[[bin]]
name = "bench"
path = "../../bench/bench.rs"

[dependencies]
aast_parser = { path = "../aast_parser" }
decl_mode_parser = { path = "../decl_mode_parser" }
decl_rust = { path = "../../../decl" }
facts_rust = { path = "../../../facts" }
ocamlrep = { path = "../../../ocamlrep" }
oxidized = { path = "../../../oxidized" }
parser = { path = "../../core" }
positioned_parser = { path = "../positioned_parser" }

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<7ceb084244748a256f28be1d047aa133e18a6a74>>
