# @generated
# @autocargo from //hphp/hack/src/hhbc:env
# Signature<<df26d08b8ad739346b6508d25a6752ccd2f93787>>
[package]
name = "env"
edition = "2018"
version = "0.0.0"
include = ["../../emitter.rs", "../../env.rs", "../../iterator.rs", "../../jump_targets.rs"]

[lib]
path = "../../env.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
rx_rust = { path = "../rx" }
bitflags = "*"
# @end of Signature<<df26d08b8ad739346b6508d25a6752ccd2f93787>>
