# @autocargo from //hphp/hack/src/hhbc:closure_convert_rust_ffi
# Signature<<c3ad79be676cfac0166296fb215d8e1d523e1513>>
[package]
name = "closure_convert_rust_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../closure_convert_ffi.rs"]

[lib]
path = "../../closure_convert_ffi.rs"

[dependencies]
aast_parser = { path = "../../../parser/cargo/aast_parser" }
lowerer = { path = "../../../parser/cargo/lowerer" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../../../parser/cargo/core_types" }
# @end of Signature<<c3ad79be676cfac0166296fb215d8e1d523e1513>>
