# @generated
# @autocargo from //hphp/hack/src/hhbc:closure_convert_rust_ffi
# Signature<<4f4e56de69b2ffa20e11e4b24755fdffafbda153>>
[package]
name = "closure_convert_rust_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../closure_convert_ffi.rs"]

[lib]
path = "../../closure_convert_ffi.rs"

[dependencies]
aast_parser = { path = "../../../parser/cargo/aast_parser" }
closure_convert_rust = { path = "../closure_convert" }
env = { path = "../env" }
lowerer = { path = "../../../parser/cargo/lowerer" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../../../parser/cargo/core_types" }
# @end of Signature<<4f4e56de69b2ffa20e11e4b24755fdffafbda153>>
