# @generated
# @autocargo from //hphp/hack/src/parser:positioned_coroutine_parser
# Signature<<574238fd21b8d4b4026df5f08d8122176a791514>>
[package]
name = "positioned_coroutine_parser"
edition = "2018"
version = "0.0.0"
include = ["../../ocaml_coroutine_state.rs", "../../ocaml_syntax.rs", "../../ocaml_syntax_generated.rs", "../../positioned_coroutine_parser.rs"]

[lib]
path = "../../positioned_coroutine_parser.rs"

[dependencies]
coroutine_smart_constructors = { path = "../coroutine_smart_constructors" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
parser = { path = "../../core" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
ocaml = "0.8"
# @end of Signature<<574238fd21b8d4b4026df5f08d8122176a791514>>
