# @generated
# @autocargo from //hphp/hack/src/ocamlrep_derive:ocamlrep_derive
# Signature<<3d5365200537424b4c1f6abda0556e891f46b09b>>
[package]
name = "ocamlrep_derive"
edition = "2018"
version = "0.0.0"
include = ["lib.rs"]

[lib]
path = "lib.rs"
proc-macro = true
test = false
doctest = false

[dependencies]
ocamlrep = { path = "../ocamlrep" }
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
synstructure = "*"
# @end of Signature<<3d5365200537424b4c1f6abda0556e891f46b09b>>
