# @generated
# @autocargo from //hphp/hack/src/parser:minimal_parser
# Signature<<d931c553737ebd2a33f53cec6cbb29db96841e43>>
[package]
name = "minimal_parser"
edition = "2018"
version = "0.0.0"
include = ["../../minimal_parser.rs", "../../minimal_smart_constructors.rs"]

[lib]
path = "../../minimal_parser.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
# @end of Signature<<d931c553737ebd2a33f53cec6cbb29db96841e43>>
