# @generated
# @autocargo from //hphp/hack/src/utils:escaper
# Signature<<bd74b9fdb06dc70b952ab2e9940aa93c47a816d2>>
[package]
name = "escaper"
edition = "2018"
version = "0.0.0"
include = ["../escaper.rs"]

[lib]
path = "../escaper.rs"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<bd74b9fdb06dc70b952ab2e9940aa93c47a816d2>>
