# @generated
# @autocargo from //hphp/hack/src/ocamlrep_ocamlpool:ocamlrep_ocamlpool
# Signature<<caa61f367879f83bf86d0540757273bea1104a82>>
[package]
name = "ocamlrep_ocamlpool"
edition = "2018"
version = "0.0.0"
include = ["*.rs"]

[lib]
path = "lib.rs"

[dependencies]
ocamlpool_rust = { path = "../utils/ocamlpool_rust" }
ocamlrep = { path = "../ocamlrep" }
ocaml = "0.8"
# @end of Signature<<caa61f367879f83bf86d0540757273bea1104a82>>
