[package]
name = "hack_ocamlrep_ocamlpool"
version = "3.72.0"
edition = "2018"

[lib]
name = "ocamlrep_ocamlpool"
path = "lib.rs"

[dependencies]
ocaml = "^0.7"
ocamlrep = {path = "../ocamlrep", package = "hack_ocamlrep"}
ocamlpool_rust = { path = "../utils/ocamlpool_rust", package = "hack_utils_ocamlpool" }
