[package]
name = "rust_parser_ffi"
version = "3.49.0"
edition = "2018"

[dependencies]
parser_rust = { path = "../..", package = "hack_parser" }
parser_core_types = { path = "../core_types", package = "hack_parser_core_types" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust", package = "hack_utils_ocamlpool" }
libc = "^0.2.60"
ocaml = "^0.7"
oxidized = {path = "../../../oxidized", package = "hack_oxidized" }
syntax_tree = {path = "../syntax_tree", package = "syntax_tree" }
rust_to_ocaml = {path = "../rust_to_ocaml", package = "rust_to_ocaml" }
ocamlrep = {path = "../../../ocamlrep", package = "hack_ocamlrep"}

[lib]
name = "rust_parser_ffi"
path = "../../rust_parser_ffi.rs"
crate-type = ["lib", "staticlib"]
