# @generated
# @autocargo from //hphp/hack/src/parser:rust_parser_ffi
# Signature<<0f893323b38269b58f1357089dc284a0278c4026>>
[package]
name = "rust_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../rust_parser_ffi.rs"]

[lib]
path = "../../rust_parser_ffi.rs"

[dependencies]
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
rust_to_ocaml = { path = "../rust_to_ocaml" }
stack_limit = { path = "../../../utils/stack_limit" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<0f893323b38269b58f1357089dc284a0278c4026>>
