# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_record_def_rust
# Signature<<c4371053fa4706a7425a6355d64924524261881f>>
[package]
name = "hhas_record_def_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_record_def.rs"]

[lib]
path = "../../hhas_record_def.rs"

[dependencies]
hhas_type = { path = "../hhas_type" }
hhbc_id_rust = { path = "../hhbc_id" }
runtime = { path = "../runtime" }
# @end of Signature<<c4371053fa4706a7425a6355d64924524261881f>>
