# @generated
# @autocargo from //hphp/hack/src/utils/ocamlpool_rust:ocamlpool_rust
# Signature<<729892e3c8af984b2641ef3d82bd0702c55e0e6f>>
[package]
name = "ocamlpool_rust"
edition = "2018"
version = "0.0.0"
include = ["lib.rs", "utils.rs"]

[lib]
path = "lib.rs"

[dependencies]
ocamlrep = { path = "../../ocamlrep" }
libc = "*"
ocaml = "*"
# @end of Signature<<729892e3c8af984b2641ef3d82bd0702c55e0e6f>>
