[package]
name = "positioned_coroutine_parser"
version = "3.49.0"
edition = "2018"

[lib]
name = "positioned_coroutine_parser"
path = "../positioned_coroutine_parser.rs"

[dependencies]
parser_core_types = { path = "../core_types", package = "hack_parser_core_types" }
parser_rust = { path = "..", package = "hack_parser" }
syntax_smart_constructors = { path = "../syntax_smart_constructors", package = "syntax_smart_constructors" }
rust_to_ocaml = { path = "../rust_to_ocaml", package = "rust_to_ocaml" }
ocaml = "^0.7"
ocamlpool_rust = { path = "../../utils/ocamlpool_rust", package = "hack_utils_ocamlpool" }
coroutine_smart_constructors = { path = "../coroutine_smart_constructors", package = "coroutine_smart_constructors" }
