# @generated
# @autocargo from //hphp/hack/src/facts:rust_facts_ffi
# Signature<<e9048af148d92a5f0373793bbafff03aee48a94f>>
[package]
name = "rust_facts_ffi"
edition = "2018"
version = "0.0.0"
include = ["../rust_facts_ffi.rs"]

[lib]
path = "../rust_facts_ffi.rs"
crate-type = ["lib", "staticlib"]

[dependencies]
facts_rust = { path = ".." }
hhbc_string_utils_rust = { path = "../../hhbc/cargo/string_utils" }
ocamlrep = { path = "../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../ocamlrep_ocamlpool" }
oxidized = { path = "../../oxidized" }
ocaml = "*"
# @end of Signature<<e9048af148d92a5f0373793bbafff03aee48a94f>>
