# @generated
# @autocargo from //hphp/hack/src/facts:rust_facts_ffi
# Signature<<11abf838d800aa71628491459649eda9858f3af4>>
[package]
name = "rust_facts_ffi"
edition = "2018"
version = "0.0.0"
include = ["../rust_facts_ffi.rs"]

[lib]
path = "../rust_facts_ffi.rs"
crate-type = ["lib", "staticlib"]

[dependencies]
facts_rust = { path = "../cargo/facts_rust" }
hhbc_string_utils_rust = { path = "../../hhbc/cargo/string_utils" }
ocamlrep = { path = "../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../ocamlrep_ocamlpool" }
oxidized = { path = "../../oxidized" }
ocaml = "0.8"
# @end of Signature<<11abf838d800aa71628491459649eda9858f3af4>>
