# @generated
# @autocargo from //hphp/hack/src/utils/html_entities:html_entities
# Signature<<0c77e34e98159f60c04ecdbcd2d5c762f3eea032>>
[package]
name = "html_entities"
edition = "2018"
version = "0.0.0"
include = ["decoder.rs", "html_entities.rs"]

[lib]
path = "html_entities.rs"

[dependencies]
ocaml_helper = { path = "../ocaml_helper" }
lazy_static = "*"
regex = "*"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<0c77e34e98159f60c04ecdbcd2d5c762f3eea032>>
