[package]
name = "html_entities"
version = "3.49.0"
edition = "2018"

[lib]
name = "html_entities"
path = "html_entities.rs"

[dependencies]
lazy_static = "^1.3.0"
regex = "^1.2.1"

[dev-dependencies]
pretty_assertions = "^0.6.1"
