# @generated
# @autocargo from //hphp/hack/src/parser:lowerer
# Signature<<85a79d53d73544e9def4ae1b488de4e95ef6a082>>
[package]
name = "lowerer"
edition = "2018"
version = "0.0.0"
include = ["../../lowerer.rs", "../../lowerer_lib.rs", "../../lowerer_modifier.rs", "../../scour_comment.rs"]

[lib]
path = "../../lowerer_lib.rs"

[dependencies]
escaper = { path = "../../../utils/escaper" }
hh_autoimport_rust = { path = "../hh_autoimport" }
html_entities = { path = "../../../utils/html_entities" }
lint_rust = { path = "../../../utils/lint" }
naming_special_names_rust = { path = "../../../naming" }
ocaml_helper = { path = "../../../utils/ocaml_helper" }
ocamlrep = { path = "../../../ocamlrep" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
stack_limit = { path = "../../../utils/stack_limit" }
itertools = "*"
lazy_static = "*"
ocaml = "*"
regex = "*"
# @end of Signature<<85a79d53d73544e9def4ae1b488de4e95ef6a082>>
