[package]
name = "hack_lowerer"
version = "3.49.0"
edition = "2018"

[lib]
name = "lowerer"
path = "../../lowerer_lib.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust", package = "hack_utils_ocamlpool" }
oxidized = {path = "../../../oxidized", package = "hack_oxidized" }
escaper = {path = "../../../utils/escaper", package = "hack_escaper" }
ocaml_helper = {path = "../../../utils/ocaml_helper", package = "hack_ocaml_helper" }
html_entities = {path = "../../../utils/html_entities", package = "html_entities" }
parser_core_types = { path = "../core_types", package = "hack_parser_core_types" }
parser_rust = { path = "../..", package = "hack_parser" }
itertools = "^0.7"
lazy_static = "^1.3.0"
ocaml = "^0.7"
regex = "^1.2.1"
naming_special_names_rust = {path = "../../../naming/", package = "naming_special_names"}
hh_autoimport_rust = { path = "../hh_autoimport", package = "hack_hh_autoimport"}
ocamlrep = {path = "../../../ocamlrep", package = "hack_ocamlrep"}
