[package]
name = "watchman_client"
version = "0.8.0"
authors = ["Wez Furlong"]
edition = "2021"
description = "a client for the Watchman file watching service"
documentation = "https://docs.rs/watchman_client"
repository = "https://github.com/facebook/watchman/"
license = "MIT"
exclude = ["examples/*"]

[dependencies]
anyhow = "1.0"
bytes = { version = "1.0", features = ["serde"] }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
maplit = "1.0"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_bser = { version = "0.3", path = "../serde_bser" }
thiserror = "1.0"
tokio = { version = "1.7.1", features = ["full", "test-util"] }
tokio-util = { version = "0.6", features = ["full"] }

[dev-dependencies]
structopt = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["handleapi", "winuser"] }
