# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_attribute_rust
# Signature<<3d81fc926211e9c9db014cd489888190ca60faee>>
[package]
name = "hhas_attribute_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_attribute.rs"]

[lib]
path = "../../hhas_attribute.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
runtime = { path = "../runtime" }
# @end of Signature<<3d81fc926211e9c9db014cd489888190ca60faee>>
