# @generated
# @autocargo from //hphp/hack/src/hhbc:closure_convert_rust
# Signature<<510a6cc59a8db4955d93debaf5486c9ff95b4d33>>
[package]
name = "closure_convert_rust"
edition = "2018"
version = "0.0.0"
include = ["../../closure_convert.rs"]

[lib]
path = "../../closure_convert.rs"

[dependencies]
ast_constant_folder_rust = { path = "../ast_constant_folder" }
ast_scope_rust = { path = "../ast_scope" }
env = { path = "../env" }
hhbc_string_utils_rust = { path = "../string_utils" }
naming_special_names_rust = { path = "../../../naming" }
ocamlrep = { path = "../../../ocamlrep" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
rx_rust = { path = "../rx" }
unique_list_rust = { path = "../unique_list" }
itertools = "*"
# @end of Signature<<510a6cc59a8db4955d93debaf5486c9ff95b4d33>>
