# @autocargo from //hphp/hack/src/hhbc:emit_memoize_helpers_rust
# Signature<<d65a6e076f384b7c69b3392abd1358b03fd1bce6>>
[package]
name = "emit_memoize_helpers_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_memoize_helpers.rs"]

[lib]
path = "../../emit_memoize_helpers.rs"

[dependencies]
emit_fatal_rust = { path = "../emit_fatal" }
hhas_param_rust = { path = "../hhas_param" }
hhbc_ast_rust = { path = "../hhbc_ast" }
instruction_sequence_rust = { path = "../instruction_sequence" }
local_rust = { path = "../local" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<d65a6e076f384b7c69b3392abd1358b03fd1bce6>>
