# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_typedef_rust
# Signature<<bc44911eddf47e33e6ea342a963498951b1bde55>>
[package]
name = "hhas_typedef_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_typedef.rs"]

[lib]
path = "../../hhas_typedef.rs"

[dependencies]
hhas_attribute_rust = { path = "../hhas_attribute" }
hhas_type = { path = "../hhas_type" }
hhbc_id_rust = { path = "../hhbc_id" }
runtime = { path = "../runtime" }
# @end of Signature<<bc44911eddf47e33e6ea342a963498951b1bde55>>
