# @autocargo from //hphp/hack/src/ocamlrep:ocamlrep
# Signature<<697c0d2aeffc13ca22a4648bc4b772b40bed2048>>
[package]
name = "ocamlrep"
edition = "2018"
version = "0.0.0"
include = ["*.rs"]

[lib]
path = "lib.rs"
# @end of Signature<<697c0d2aeffc13ca22a4648bc4b772b40bed2048>>
