# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_body_rust
# Signature<<05b7da962d8e94cf471b53865f2b86023dcf492b>>
[package]
name = "emit_body_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_body.rs", "../../emit_statement.rs", "../../reified_generics_helpers.rs", "../../try_finally_rewriter.rs"]

[lib]
path = "../../emit_body.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
emit_adata_rust = { path = "../emit_adata" }
emit_expression_rust = { path = "../.." }
emit_fatal_rust = { path = "../emit_fatal" }
emit_pos_rust = { path = "../emit_pos" }
emit_type_hint_rust = { path = "../emit_type_hint" }
env = { path = "../env" }
hhbc_ast_rust = { path = "../hhbc_ast" }
hhbc_string_utils_rust = { path = "../string_utils" }
instruction_sequence_rust = { path = "../instruction_sequence" }
label_rewriter_rust = { path = "../label_rewriter" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
naming_special_names_rust = { path = "../../../naming" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
bitflags = "1.2"
# @end of Signature<<05b7da962d8e94cf471b53865f2b86023dcf492b>>
