# @autocargo from //hphp/hack/src/hhbc:emit_fatal_rust
# Signature<<338027c9606e7af8bc13d0cd143332d1a09ef401>>
[package]
name = "emit_fatal_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_fatal.rs"]

[lib]
path = "../../emit_fatal.rs"

[dependencies]
emit_pos_rust = { path = "../emit_pos" }
env = { path = "../env" }
hhbc_ast_rust = { path = "../hhbc_ast" }
instruction_sequence_rust = { path = "../instruction_sequence" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<338027c9606e7af8bc13d0cd143332d1a09ef401>>
