# @autocargo from //hphp/hack/src/hhbc:rx_rust
# Signature<<7c9ee5915ea72973751449b4a305497df9cb147e>>
[package]
name = "rx_rust"
edition = "2018"
version = "0.0.0"
include = ["../../rx.rs"]

[lib]
path = "../../rx.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<7c9ee5915ea72973751449b4a305497df9cb147e>>
