# @generated
# @autocargo from //hphp/hack/src/hhbc:rx_rust
# Signature
[package]
name = "rx_rust"
edition = "2018"
version = "0.0.0"
include = ["../../rx.rs"]

[lib]
path = "../../rx.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_derive = { path = "../../../ocamlrep_derive" }
oxidized = { path = "../../../oxidized" }
# @end of Signature
