# @generated
# @autocargo from //hphp/hack/src/parser:positioned_coroutine_parser_ffi
# Signature<<91bf053666f081e87994d3ccd35a86328e150f5c>>
[package]
name = "positioned_coroutine_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../positioned_coroutine_parser_ffi.rs"]

[lib]
path = "../../positioned_coroutine_parser_ffi.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
positioned_coroutine_parser = { path = "../positioned_coroutine_parser" }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<91bf053666f081e87994d3ccd35a86328e150f5c>>
