# @generated
# @autocargo from //hphp/hack/src/parser:positioned_coroutine_parser_ffi
# Signature<<c9d6f4904f841ce0acdfd1c13076ee28543b6770>>
[package]
name = "positioned_coroutine_parser_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../positioned_coroutine_parser_ffi.rs"]

[lib]
path = "../../positioned_coroutine_parser_ffi.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
positioned_coroutine_parser = { path = "../positioned_coroutine_parser" }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<c9d6f4904f841ce0acdfd1c13076ee28543b6770>>
