# @autocargo from //hphp/hack/src/utils/lint:lint_rust
# Signature<<e316138011ee42849ff0807332d6b679fa931d5a>>
[package]
name = "lint_rust"
edition = "2018"
version = "0.0.0"
include = ["lint.rs"]

[lib]
path = "lint.rs"

[dependencies]
ocamlrep = { path = "../../ocamlrep" }
ocamlrep_derive = { path = "../../ocamlrep_derive" }
oxidized = { path = "../../oxidized" }
# @end of Signature<<e316138011ee42849ff0807332d6b679fa931d5a>>
