# @generated
# @autocargo from //hphp/hack/src/typing:typing_env_rust
# Signature
[package]
name = "typing_env_rust"
edition = "2018"
version = "0.0.0"
include = ["../../../typing_env.rs", "../../../typing_env_return_info.rs", "../../../typing_env_rust.rs", "../../../typing_env_types.rs", "../../../typing_inference_env.rs", "../../../typing_tyvar_occurrences.rs"]

[lib]
path = "../../../typing_env_rust.rs"

[dependencies]
oxidized = { path = "../../../../oxidized" }
typing_collections_rust = { path = "../typing_collections_rust" }
typing_defs_rust = { path = "../typing_defs_rust" }
bumpalo = { version = "3.1.2", features = ["collections"] }
im-rc = { version = "14.2", features = ["serde"] }
# @end of Signature
