# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_native_opcode_rust
# Signature
[package]
name = "emit_native_opcode_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_native_opcode.rs"]

[lib]
path = "../../emit_native_opcode.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
emit_body_rust = { path = "../emit_body" }
emit_fatal_rust = { path = "../emit_fatal" }
emit_param_rust = { path = "../emit_param" }
env = { path = "../env" }
hhas_body_rust = { path = "../hhas_body" }
instruction_sequence_rust = { path = "../instruction_sequence" }
local_rust = { path = "../local" }
oxidized = { path = "../../../oxidized" }
# @end of Signature
