# @generated
# @autocargo from //hphp/hack/src/hhbc:compile_rust
# Signature<<dbbd25eb01fc02c3a86c2886d92f9778ba5851fa>>
[package]
name = "compile_rust"
edition = "2018"
version = "0.0.0"
include = ["../../compile.rs"]

[lib]
path = "../../compile.rs"

[dependencies]
aast_parser = { path = "../../../parser/cargo/aast_parser" }
ocamlrep = { path = "../../../ocamlrep" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../../../parser/cargo/core_types" }
bitflags = "*"
# @end of Signature<<dbbd25eb01fc02c3a86c2886d92f9778ba5851fa>>
