# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_program_rust
# Signature
[package]
name = "hhas_program_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_program.rs"]

[lib]
path = "../../hhas_program.rs"

[dependencies]
hhas_attribute_rust = { path = "../hhas_attribute" }
hhas_body_rust = { path = "../hhas_body" }
hhas_function_rust = { path = "../hhas_function" }
hhas_record_def_rust = { path = "../hhas_record_def" }
hhas_symbol_refs_rust = { path = "../hhas_symbol_refs" }
hhas_typedef_rust = { path = "../hhas_typedef" }
# @end of Signature
