# @autocargo from //hphp/hack/src/hhbc:options_ffi
# Signature<<3e6234b5e8125775c2f0e6bf62dd1b2deea52685>>
[package]
name = "options_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../options_ffi.rs"]

[lib]
path = "../../options_ffi.rs"

[dependencies]
hhbc_string_utils_rust = { path = "../string_utils" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
options = { path = "../options" }
ocaml = "*"
# @end of Signature<<3e6234b5e8125775c2f0e6bf62dd1b2deea52685>>
