# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_expression_rust
# Signature<<57fa783b9ff0e9732fe5c172f213173d78e7ed7d>>
[package]
name = "emit_expression_rust"
edition = "2018"
version = "0.0.0"
include = ["emit_expression.rs"]

[lib]
path = "emit_expression.rs"

[dependencies]
ast_class_expr_rust = { path = "cargo/ast_class_expr" }
ast_constant_folder_rust = { path = "cargo/ast_constant_folder" }
ast_scope_rust = { path = "cargo/ast_scope" }
emit_adata_rust = { path = "cargo/emit_adata" }
emit_fatal_rust = { path = "cargo/emit_fatal" }
emit_pos_rust = { path = "cargo/emit_pos" }
emit_symbol_refs_rust = { path = "cargo/emit_symbol_refs" }
emit_type_constant_rust = { path = "cargo/emit_type_constant" }
env = { path = "cargo/env" }
hhas_symbol_refs_rust = { path = "cargo/hhas_symbol_refs" }
hhas_type = { path = "cargo/hhas_type" }
hhbc_ast_rust = { path = "cargo/hhbc_ast" }
hhbc_id_rust = { path = "cargo/hhbc_id" }
hhbc_string_utils_rust = { path = "cargo/string_utils" }
instruction_sequence_rust = { path = "cargo/instruction_sequence" }
label_rust = { path = "cargo/label" }
local_rust = { path = "cargo/local" }
naming_special_names_rust = { path = "../naming" }
options = { path = "cargo/options" }
oxidized = { path = "../oxidized" }
runtime = { path = "cargo/runtime" }
scope_rust = { path = "cargo/scope" }
# @end of Signature<<57fa783b9ff0e9732fe5c172f213173d78e7ed7d>>
