# @generated
# @autocargo from //hphp/hack/src/hhbc:label_rewriter_rust
# Signature<<85454322923208b1ac3729db235fc78d42572705>>
[package]
name = "label_rewriter_rust"
edition = "2018"
version = "0.0.0"
include = ["../../label_rewriter.rs"]

[lib]
path = "../../label_rewriter.rs"

[dependencies]
env = { path = "../env" }
hhas_param_rust = { path = "../hhas_param" }
hhbc_ast_rust = { path = "../hhbc_ast" }
instruction_sequence_rust = { path = "../instruction_sequence" }
label_rust = { path = "../label" }
# @end of Signature<<85454322923208b1ac3729db235fc78d42572705>>
