# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_symbol_refs_rust
# Signature<<25f37fd538656b9b8bedc009287a9bfcb47c4ea5>>
[package]
name = "emit_symbol_refs_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_symbol_refs.rs"]

[lib]
path = "../../emit_symbol_refs.rs"

[dependencies]
env = { path = "../env" }
hhas_symbol_refs_rust = { path = "../hhas_symbol_refs" }
hhbc_id_rust = { path = "../hhbc_id" }
# @end of Signature<<25f37fd538656b9b8bedc009287a9bfcb47c4ea5>>
