# @generated
# @autocargo from //hphp/hack/src/hhbc:options
# Signature<<dfafef0e683c9fc76088699b83d2ea0c41c3b796>>
[package]
name = "options"
edition = "2018"
version = "0.0.0"
include = ["../../options.rs", "../../options_cli.rs"]

[lib]
path = "../../options.rs"

[dependencies]
options_serde = { path = "../options_serde" }
bitflags = "1.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<dfafef0e683c9fc76088699b83d2ea0c41c3b796>>
