# @generated
# @autocargo from //hphp/hack/src/parser:coroutine_parser_leak_tree_ffi
# Signature<<6ecd5f9c92ee3bf8af565d955330bb6a5e852fe4>>
[package]
name = "coroutine_parser_leak_tree_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_parser_leak_tree_ffi.rs"]

[lib]
path = "../../coroutine_parser_leak_tree_ffi.rs"

[dependencies]
coroutine_parser_leak_tree = { path = "../../api/cargo/coroutine_parser_leak_tree" }
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../core_types" }
rust_parser_ffi = { path = "../rust_parser_ffi" }
rust_to_ocaml = { path = "../rust_to_ocaml" }
syntax_tree = { path = "../syntax_tree" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<6ecd5f9c92ee3bf8af565d955330bb6a5e852fe4>>
