# @generated
# @autocargo from //hphp/hack/src/facts:facts_smart_constructors
# Signature<<7f6283cb0f4251a83676a79ec6b76e0773f2e41c>>
[package]
name = "facts_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../facts_smart_constructors.rs", "../../facts_smart_constructors_generated.rs"]

[lib]
path = "../../facts_smart_constructors.rs"

[dependencies]
escaper = { path = "../../../utils/escaper" }
flatten_smart_constructors = { path = "../../../parser/cargo/flatten_smart_constructors" }
hhbc_string_utils_rust = { path = "../../../hhbc/cargo/string_utils" }
ocamlrep = { path = "../../../ocamlrep" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../../../parser/cargo/core_types" }
smart_constructors = { path = "../../../parser/cargo/smart_constructors" }
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<7f6283cb0f4251a83676a79ec6b76e0773f2e41c>>
