[package]
name = "hack_parser_core_types"
version = "3.49.0"
edition = "2018"

[lib]
name = "parser_core_types"
path = "../../parser_core_types_lib.rs"

[dependencies]
line_break_map = {path = "../../../utils/line_break_map", package = "hack_line_break_map"}
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust", package = "hack_utils_ocamlpool" }
ocamlrep = {path = "../../../ocamlrep", package = "hack_ocamlrep"}
oxidized = {path = "../../../oxidized", package = "hack_oxidized"}
itertools = "^0.7"
