[package]
name = "hack_hhbc_string_utils"
version = "3.49.0"
edition = "2018"

[lib]
name = "hhbc_string_utils_rust"
path = "../../string_utils.rs"

[dependencies]
escaper = { path = "../../../utils/escaper", package = "hack_escaper" }
naming_special_names_rust = { path = "../../../naming", package = "naming_special_names" }
lazy_static = "^1.3.0"
regex = "^1.2.1"
libc = "^0.2.60"

[dev-dependencies]
pretty_assertions = "^0.6.1"
