# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_string_utils_rust
# Signature<<3b0ee71473cee7157f6144fc5f4fc4cf0fcafd4a>>
[package]
name = "hhbc_string_utils_rust"
edition = "2018"
version = "0.0.0"
include = ["../../string_utils.rs"]

[lib]
path = "../../string_utils.rs"

[dependencies]
escaper = { path = "../../../utils/escaper" }
naming_special_names_rust = { path = "../../../naming" }
lazy_static = "*"
libc = "*"
regex = "*"

[dev-dependencies]
pretty_assertions = "*"
# @end of Signature<<3b0ee71473cee7157f6144fc5f4fc4cf0fcafd4a>>
