# @generated
# @autocargo from //hphp/hack/src/hhbc:instruction_sequence_rust
# Signature
[package]
name = "instruction_sequence_rust"
edition = "2018"
version = "0.0.0"
include = ["../../instruction_sequence.rs"]

[lib]
path = "../../instruction_sequence.rs"

[dependencies]
env = { path = "../env" }
hhbc_ast_rust = { path = "../hhbc_ast" }
hhbc_id_rust = { path = "../hhbc_id" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
runtime = { path = "../runtime" }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature
