# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_hhas_rust
# Signature
[package]
name = "hhbc_hhas_rust"
edition = "2018"
version = "0.0.0"
include = ["../../print.rs", "../../print_env.rs", "../../write.rs"]

[lib]
path = "../../print.rs"

[dependencies]
escaper = { path = "../../../utils/escaper" }
hhas_body_rust = { path = "../hhas_body" }
hhas_function_rust = { path = "../hhas_function" }
hhas_param_rust = { path = "../hhas_param" }
hhas_pos_rust = { path = "../hhas_pos" }
hhas_program_rust = { path = "../hhas_program" }
hhas_record_def_rust = { path = "../hhas_record_def" }
hhas_type = { path = "../hhas_type" }
hhbc_ast_rust = { path = "../hhbc_ast" }
hhbc_id_rust = { path = "../hhbc_id" }
instruction_sequence_rust = { path = "../instruction_sequence" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
thiserror = "1.0"
# @end of Signature
