# @generated
# @autocargo from //hphp/hack/src/parser:rust_to_ocaml
# Signature<<15f98d4d061d98a0d16e781c18f20bb53fa84aa9>>
[package]
name = "rust_to_ocaml"
edition = "2018"
version = "0.0.0"
include = ["../../rust_to_ocaml.rs"]

[lib]
path = "../../rust_to_ocaml.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
parser_core_types = { path = "../core_types" }
parser_rust = { path = "../.." }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<15f98d4d061d98a0d16e781c18f20bb53fa84aa9>>
