# @generated
# @autocargo from //hphp/hack/src/parser:rust_to_ocaml
# Signature<<ea35df3dad47aef3cf6fb86f4d637cb148365670>>
[package]
name = "rust_to_ocaml"
edition = "2018"
version = "0.0.0"
include = ["../../rust_to_ocaml.rs"]

[lib]
path = "../../rust_to_ocaml.rs"

[dependencies]
ocamlpool_rust = { path = "../../../utils/ocamlpool_rust" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
parser = { path = "../../core" }
parser_core_types = { path = "../core_types" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<ea35df3dad47aef3cf6fb86f4d637cb148365670>>
