[package]
name = "hh_fanout_oss"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/facebook/hhvm"
license = "MIT"

[[bin]]
name = "hh_fanout"
path = "../../hh_fanout_oss/main.rs"

[dependencies]
clap = { version = "4.5.42", features = ["derive", "env", "string", "unicode", "wrap_help"] }
hh_fanout_build = { version = "0.0.0", path = "../hh_fanout_build" }
