# @autocargo from //hphp/hack/src/hhbc:emit_program_rust
# Signature<<107171e264b52d6cf5a72d8700fd58667eb450e4>>
[package]
name = "emit_program_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_program.rs"]

[lib]
path = "../../emit_program.rs"

[dependencies]
env = { path = "../env" }
options = { path = "../options" }
bitflags = "*"
# @end of Signature<<107171e264b52d6cf5a72d8700fd58667eb450e4>>
