# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_program_rust
# Signature<<13abc72863428994844c6ed4c99ec31ed1ed2cec>>
[package]
name = "emit_program_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_program.rs"]

[lib]
path = "../../emit_program.rs"

[dependencies]
env = { path = "../env" }
options = { path = "../options" }
bitflags = "1.2"
# @end of Signature<<13abc72863428994844c6ed4c99ec31ed1ed2cec>>
