# @autocargo from //hphp/hack/src/hh_codegen:hh_codegen
# Signature<<5dd4d1b935e85a3fdce384e2d42083853deb9999>>
[package]
name = "hh_codegen"
edition = "2018"
version = "0.0.0"
include = ["**/*.rs"]

[[bin]]
name = "hh_codegen"
path = "hh_codegen.rs"

[dependencies]
clap = "*"
itertools = "*"
proc-macro2 = "*"
quote = "*"
rust-crypto = "*"
syn = { version = "*", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
synstructure = "*"
# @end of Signature<<5dd4d1b935e85a3fdce384e2d42083853deb9999>>
