[package]
name = "hack_hh_codegen"
version = "3.49.0"
edition = "2018"
autobins = false

[[bin]]
name = "hh_codegen"
path = "./hh_codegen.rs"

[dependencies.syn]
version = "^1.0.5"
features = ["full", "extra-traits", "visit-mut", "visit"]

[dependencies]
proc-macro2 = "^1.0.4"
quote ="^1.0.2"
synstructure = "^0.12.0"
itertools = "^0.7"
clap = "^2.33.0"
