# @generated
# @autocargo from //hphp/hack/src/decl:direct_decl_smart_constructors
# Signature<<bafe6ec23365353c8a858c51b86f43f8773aa127>>
[package]
name = "direct_decl_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../direct_decl_smart_constructors.rs", "../direct_decl_smart_constructors_generated.rs"]

[lib]
path = "../direct_decl_smart_constructors.rs"

[dependencies]
flatten_smart_constructors = { path = "../../parser/cargo/flatten_smart_constructors" }
hh_autoimport_rust = { path = "../../parser/cargo/hh_autoimport" }
hhbc_string_utils_rust = { path = "../../hhbc/cargo/string_utils" }
naming_special_names_rust = { path = "../../naming" }
ocamlrep = { path = "../../ocamlrep" }
oxidized = { path = "../../oxidized" }
parser_core_types = { path = "../../parser/cargo/core_types" }
smart_constructors = { path = "../../parser/cargo/smart_constructors" }
rust-crypto = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<bafe6ec23365353c8a858c51b86f43f8773aa127>>
